#!/bin/sh

set -e

# Initial setup
adduser reactive-sandbox -u 1000 -D

# Dependencies
# apk add --no-cache bash openjdk8-jre-base supervisor postgresql=11.0-r0
apk add --no-cache bash openjdk8-jre-base supervisor


# Download & Extract
cassandra_url="https://archive.apache.org/dist/cassandra/3.0.15/apache-cassandra-3.0.15-bin.tar.gz"
# elasticsearch_url="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.5.tar.gz"
elasticsearch_url="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.4.2.tar.gz"
logstash_url="https://artifacts.elastic.co/downloads/logstash/logstash-6.4.2.tar.gz"
kibana_url="https://artifacts.elastic.co/downloads/kibana/kibana-6.4.2-linux-x86_64.tar.gz"
kafka_url="http://mirrors.ibiblio.org/apache/kafka/1.0.0/kafka_2.11-1.0.0.tgz"
zookeeper_url="http://mirrors.ibiblio.org/apache/zookeeper/zookeeper-3.4.11/zookeeper-3.4.11.tar.gz"

mkdir -p /root/build
cd /root/build

wget -q "$cassandra_url" -O cassandra.tar.gz
wget -q "$elasticsearch_url" -O elasticsearch.tar.gz
wget -q "$logstash_url" -O logstash.tar.gz
wget -q "$kibana_url" -O kibana.tar.gz
wget -q "$kafka_url" -O kafka.tar.gz
wget -q "$zookeeper_url" -O zookeeper.tar.gz

mkdir -p /opt/cassandra
tar --strip-components 1 -x -C /opt/cassandra -f cassandra.tar.gz

mkdir -p /opt/elasticsearch
tar --strip-components 1 -x -C /opt/elasticsearch -f elasticsearch.tar.gz

mkdir -p /opt/logstash
tar --strip-components 1 -x -C /opt/logstash -f logstash.tar.gz

mkdir -p /opt/kibana
tar --strip-components 1 -x -C /opt/kibana -f kibana.tar.gz

mkdir -p /opt/kafka
tar --strip-components 1 -x -C /opt/kafka -f kafka.tar.gz

mkdir -p /opt/zookeeper
tar --strip-components 1 -x -C /opt/zookeeper -f zookeeper.tar.gz

# Directories & Permissions
chown -R reactive-sandbox /opt
mkdir -p /etc/supervisor.d/

# Clean up

cd /
rm -rf /root/build

